injectEnvironmentFiles:
  - .env?

nodeLinker: node-modules

npmPublishRegistry: 'https://npm.pkg.github.com'

npmScopes:
  arke-systems:
    npmAlwaysAuth: true
    npmAuthToken: '${GitHub_Package_Token}'
    npmRegistryServer: 'https://npm.pkg.github.com'

preferInteractive: true
